### ISSUE TITLE
Support for new versions

### ISSUE THREAD

**Issue by grzesuav** [davido/bazel-alpine-package#5]
Hi,

this project will be updating versions accordingly (now there is 0.18.0) or it is abandoned or there is alternative ?

**Comment by davido** [comment]
Yes, there should be new versions. I will release new one shortly.

**Comment by grzesuav** [comment]
Great ! Will be waiting

**Comment by davido** [comment]
I'm seeing some failures during the build of 0.18.0 package and filed this issue: [1].

* [1] https://github.com/bazelbuild/bazel/issues/6528

**Comment by davido** [comment]
https://github.com/davido/bazel-alpine-package/releases/tag/0.19.0
